/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hello VuePress",
  "description": "Just playing around",
  "base": "/Honkai-Star-Rail-Docs/",
  "headTags": [],
  "pages": [
    {
      "title": "Honkai-Star-Rail-Docs",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-754767cf",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/1.html",
      "relativePath": "guide/1.md",
      "key": "v-0ffc295f",
      "path": "/guide/1.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/2.html",
      "relativePath": "guide/2.md",
      "key": "v-625adfff",
      "path": "/guide/2.html"
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "plugins",
        "collapsable": false,
        "children": [
          {
            "title": "去掉全部console测试",
            "path": "/guide/1.md"
          }
        ]
      },
      {
        "title": "loaders",
        "collapsable": false,
        "children": [
          {
            "title": "生成打包信息",
            "path": "/guide/2.md"
          }
        ]
      }
    ]
  }
}