/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "崩坏：星穹铁道小助手文档",
  "description": "崩坏：星穹铁道小助手文档",
  "base": "/Honkai-Star-Rail-Docs/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/index.md",
      "key": "v-035fa638",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "重要提示",
          "slug": "重要提示"
        },
        {
          "level": 2,
          "title": "Python的安装",
          "slug": "python的安装"
        },
        {
          "level": 2,
          "title": "启动星穹铁道小助手",
          "slug": "启动星穹铁道小助手"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/love!.png",
        "actions": [
          {
            "text": "快速上手",
            "link": "/guide/",
            "type": "primary"
          },
          {
            "text": "项目简介",
            "link": "/config/",
            "type": "secondary"
          }
        ],
        "features": [
          {
            "title": "嘤嘤嘤",
            "details": "嘤嘤，嘤嘤嘤"
          },
          {
            "title": "嘤嘤嘤",
            "details": "嘤嘤，嘤嘤嘤"
          },
          {
            "title": "嘤嘤嘤",
            "details": "嘤嘤，嘤嘤嘤"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2023-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-754767cf",
      "path": "/"
    },
    {
      "title": "配置",
      "frontmatter": {},
      "regularPath": "/config/",
      "relativePath": "config/index.md",
      "key": "v-15fd5918",
      "path": "/config/",
      "headers": [
        {
          "level": 2,
          "title": "配置相关",
          "slug": "配置相关"
        },
        {
          "level": 2,
          "title": "完整配置参考",
          "slug": "完整配置参考"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "配置",
        "link": "/config/"
      },
      {
        "text": "反馈",
        "items": [
          {
            "text": "QQ群",
            "link": "https://qm.qq.com/cgi-bin/qm/qr?k=xdCO46fHlVcY7D2L7elXzqcxL3nyTGnW&jump_from=webapi&authKey=uWZooQ2szv+nG/re7luCKn8LW1KibSb0vvi0FycA45Mglm5AGM1GP2iJ+SiWmDwg"
          },
          {
            "text": "Telegram Group",
            "link": "https://t.me/+yeQEhnuT9O41NDM1"
          }
        ]
      },
      {
        "text": "Github",
        "link": "https://github.com/Starry-Wind/SRA"
      }
    ],
    "sidebar": [
      {
        "title": "首页",
        "path": "/"
      },
      {
        "title": "指南",
        "path": "/guide/"
      },
      {
        "title": "配置",
        "path": "/config/"
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}